packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.0"
  "react": "^19.1.0"
  "react-dom": "^19.1.0"
  "typescript": "^5.9.2"
    
recursiveInstall: true

linkWorkspacePackages: true
preferWorkspacePackages: true