packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.0"
  "react": "^19.1.0"
  "react-dom": "^19.1.0"
  "typescript": "^5.9.2"
    
# NOTE These don't work here - they are only reconized in .npmrc
# This could be because of the pnpm version
# Temporary fix is to add workspace packages with --workspace flag
recursiveInstall: true
linkWorkspacePackages: true
preferWorkspacePackages: true